### ISSUE TITLE
Create example for new location layer functionality.

### ISSUE THREAD

**Issue by MaximAlien** [mapbox/mapbox-navigation-ios-examples#115]
In scope of https://github.com/mapbox/mapbox-navigation-ios/pull/2968 new functionality, which allows to provide custom location layers was implemented. To showcase various approaches (e.g. custom location puck in `2D` and `3D`) of location puck customization new example application should be created.

/cc @ShanMa1991

**Comment by ShanMa1991** [comment]
Fixed in #117
