### ISSUE TITLE
Route initialization example crashes.

### ISSUE THREAD

**Issue by MaximAlien** [mapbox/mapbox-navigation-ios-examples#177]
It's not possible to use `Route initialization` example at this time due to crashes. Here's example of a crash log:

[Navigation-Examples-2022-06-17-154038.txt](https://github.com/mapbox/mapbox-navigation-ios-examples/files/8931647/Navigation-Examples-2022-06-17-154038.txt)

**Comment by kried** [comment]
The reason for the crash is fixed in v2.10.0-beta.1
