### ISSUE TITLE
Update styled UI elements example.

### ISSUE THREAD

**Issue by MaximAlien** [mapbox/mapbox-navigation-ios-examples#179]
At this point styled UI elements [example](https://github.com/mapbox/mapbox-navigation-ios-examples/blob/main/Navigation-Examples/Examples/Styled-UI-Elements.swift) applies global styling. After landing https://github.com/mapbox/mapbox-navigation-ios/pull/3922 this is no longer correct and style should be applied for iOS and CarPlay individually. In scope of this ticket this example should be updated to only apply style changes for iOS.

**Comment by ShanMa1991** [comment]
It has been fixed by https://github.com/mapbox/mapbox-navigation-ios-examples/pull/188
