### ISSUE TITLE
Create example which allows to style route line in NavigationViewController.

### ISSUE THREAD

**Issue by MaximAlien** [mapbox/mapbox-navigation-ios-examples#84]
Similarly to https://github.com/mapbox/navigation-ios-examples/issues/81 example which allows to style route line in `NavigationViewController` should be implemented.

**Note:** Certain delegate methods will not work at this point due to Navigation SDK issue reported in https://github.com/mapbox/mapbox-navigation-ios/issues/2753. Also since `NavigationViewController` doesn't support the ability to show alternative route lines, methods which allow to style alternative routes will not have any effect.

**Comment by truburt** [comment]
@pjleonard37 , what would be the next steps for this issue?

**Comment by pjleonard37** [comment]
@truburt - next step is updating the linked PR for v2.0. I'll work on that
