### ISSUE TITLE
Add example of observing electronic horizon notifications

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios-examples#88]
mapbox/mapbox-navigation-ios#2834 added some code to the Example application that demonstrates observing electronic horizon notifications and printing out the name of the upcoming cross street. I think that basic example is concise but instructive enough to warrant an example in this repository.

/cc @mapbox/navigation-ios

**Comment by 1ec5** [comment]
This example would probably make much more sense if we have an example of installing a PassiveLocationManager during free driving: #72.

**Comment by azarovalex** [comment]
PR was merged.
