### ISSUE TITLE
Add Offline Regions Example

### ISSUE THREAD

**Issue by Udumft** [mapbox/mapbox-navigation-ios-examples#96]
Add an example for Offline Regions feature.
This example should cover:
* Creating a custom `TileStore`
* Downloading a region (could have several hard-coded offline regions to download)
* Listing downloaded regions
* Refreshing outdated region
    A simplest example would be to attempt to refresh all existing regions.
* Removing a region

**Comment by MaximAlien** [comment]
@jill-cardamon, I can see that https://github.com/mapbox/mapbox-navigation-ios-examples/pull/114 was merged. Can we close this ticket?
