### ISSUE TITLE
Building example project in Xcode 12.4 Error

### ISSUE THREAD

**Issue by kaveh1018** [mapbox/mapbox-navigation-ios-examples#99]
When i tried to build and run for Device (iphone 11 with iOS 14 )

building for iOS, but linking in dylib file (/Users/kavehmohammadpour/Library/Developer/Xcode/DerivedData/Navigation-Examples-awnrhthmcpxmivdzpehdnkettjdb/Build/Products/Debug-iphoneos/MapboxAccounts.framework/MapboxAccounts) built for Mac Catalyst, file '/Users/kavehmohammadpour/Library/Developer/Xcode/DerivedData/Navigation-Examples-awnrhthmcpxmivdzpehdnkettjdb/Build/Products/Debug-iphoneos/MapboxAccounts.framework/MapboxAccounts' for architecture arm64

When i tried to run on simulator:

Ld /Users/kavehmohammadpour/Library/Developer/Xcode/DerivedData/Navigation-Examples-awnrhthmcpxmivdzpehdnkettjdb/Build/Products/Debug-iphonesimulator/MapboxCoreNavigation/MapboxCoreNavigation.framework/MapboxCoreNavigation normal (in target 'MapboxCoreNavigation' from project 'Pods')
    cd /Users/kavehmohammadpour/Desktop/MapBox-Test/mapbox-navigation-ios-examples/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target x86_64-apple-ios12.0-simulator -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk -L/Users/kavehmohammadpour/Library/Developer/Xcode/DerivedData/Navigation-Examples-awnrhthmcpxmivdzpehdnkettjdb/Build/Products/Debug-iphonesimulator/MapboxCoreNavigation -F/Users/kavehmohammadpour/Library/Developer/Xcode/DerivedData/Navigation-Examples-awnrhthmcpxmivdzpehdnkettjdb/Build/Products/Debug-iphonesimulator/MapboxCoreNavigation -F/Users/kavehmohammadpour/Library/Developer/Xcode/DerivedData/Navigation-Examples-awnrhthmcpxmivdzpehdnkettjdb/Build/Products/Debug-iphonesimulator/MapboxDirections -F/Users/kavehmohammadpour/Library/Developer/Xcode/DerivedData/Navigation-Examples-awnrhthmcpxmivdzpehdnkettjdb/Build/Products/Debug-iphonesimulator/MapboxMobileEvents -F/Users/kavehmohammadpour/Library/Developer/Xcode/DerivedData/Navigation-Examples-awnrhthmcpxmivdzpehdnkettjdb/Build/Products/Debug-iphonesimulator/Polyline -F/Users/kavehmohammadpour/Library/Developer/Xcode/DerivedData/Navigation-Examples-awnrhthmcpxmivdzpehdnkettjdb/Build/Products/Debug-iphonesimulator/Turf -F/Users/kavehmohammadpour/Desktop/MapBox-Test/mapbox-navigation-ios-examples/Pods/MapboxAccounts -F/Users/kavehmohammadpour/Desktop/MapBox-Test/mapbox-navigation-ios-examples/Pods/MapboxAccounts/MapboxAccounts.xcframework/ios-arm64_armv7 -F/Users/kavehmohammadpour/Desktop/MapBox-Test/mapbox-navigation-ios-examples/Pods/MapboxAccounts/MapboxAccounts.xcframework/ios-arm64_i386_x86_64-simulator -F/Users/kavehmohammadpour/Desktop/MapBox-Test/mapbox-navigation-ios-examples/Pods/MapboxAccounts/MapboxAccounts.xcframework/ios-arm64_x86_64-maccatalyst -F/Users/kavehmohammadpour/Desktop/MapBox-Test/mapbox-navigation-ios-examples/Pods/MapboxCommon -F/Users/kavehmohammadpour/Desktop/MapBox-Test/mapbox-navigation-ios-examples/Pods/MapboxCommon/MapboxCommon.xcframework/ios-arm64_armv7 -F/Users/kavehmohammadpour/Desktop/MapBox-Test/mapbox-navigation-ios-examples/Pods/MapboxCommon/MapboxCommon.xcframework/ios-arm64_i386_x86_64-simulator -F/Users/kavehmohammadpour/Desktop/MapBox-Test/mapbox-navigation-ios-examples/Pods/MapboxCommon/MapboxCommon.xcframework/ios-x86_64-maccatalyst -F/Users/kavehmohammadpour/Desktop/MapBox-Test/mapbox-navigation-ios-examples/Pods/MapboxNavigationNative -F/Users/kavehmohammadpour/Desktop/MapBox-Test/mapbox-navigation-ios-examples/Pods/MapboxNavigationNative/MapboxNavigationNative.xcframework/ios-arm64_armv7 -F/Users/kavehmohammadpour/Desktop/MapBox-Test/mapbox-navigation-ios-examples/Pods/MapboxNavigationNative/MapboxNavigationNative.xcframework/ios-arm64_i386_x86_64-simulator -filelist /Users/kavehmohammadpour/Library/Developer/Xcode/DerivedData/Navigation-Examples-awnrhthmcpxmivdzpehdnkettjdb/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/MapboxCoreNavigation.build/Objects-normal/x86_64/MapboxCoreNavigation.LinkFileList -install_name @rpath/MapboxCoreNavigation.framework/MapboxCoreNavigation -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/kavehmohammadpour/Library/Developer/Xcode/DerivedData/Navigation-Examples-awnrhthmcpxmivdzpehdnkettjdb/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/MapboxCoreNavigation.build/Objects-normal/x86_64/MapboxCoreNavigation_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/kavehmohammadpour/Library/Developer/Xcode/DerivedData/Navigation-Examples-awnrhthmcpxmivdzpehdnkettjdb/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/MapboxCoreNavigation.build/Objects-normal/x86_64/MapboxCoreNavigation.swiftmodule -framework MapboxAccounts -framework MapboxCommon -framework MapboxNavigationNative -framework Foundation -framework MapboxDirections -framework MapboxMobileEvents -framework Turf -Xlinker -no_adhoc_codesign -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/kavehmohammadpour/Library/Developer/Xcode/DerivedData/Navigation-Examples-awnrhthmcpxmivdzpehdnkettjdb/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/MapboxCoreNavigation.build/Objects-normal/x86_64/MapboxCoreNavigation_dependency_info.dat -o /Users/kavehmohammadpour/Library/Developer/Xcode/DerivedData/Navigation-Examples-awnrhthmcpxmivdzpehdnkettjdb/Build/Products/Debug-iphonesimulator/MapboxCoreNavigation/MapboxCoreNavigation.framework/MapboxCoreNavigation

ld: warning: ld: warning: ignoring file /Users/kavehmohammadpour/Desktop/MapBox-Test/mapbox-navigation-ios-examples/Pods/MapboxAccounts/MapboxAccounts.xcframework/ios-arm64_armv7/MapboxAccounts.framework/MapboxAccounts, missing required architecture x86_64 in file /Users/kavehmohammadpour/Desktop/MapBox-Test/mapbox-navigation-ios-examples/Pods/MapboxAccounts/MapboxAccounts.xcframework/ios-arm64_armv7/MapboxAccounts.framework/MapboxAccounts (2 slices)ignoring file /Users/kavehmohammadpour/Desktop/MapBox-Test/mapbox-navigation-ios-examples/Pods/MapboxCommon/MapboxCommon.xcframework/ios-arm64_armv7/MapboxCommon.framework/MapboxCommon, missing required architecture x86_64 in file /Users/kavehmohammadpour/Desktop/MapBox-Test/mapbox-navigation-ios-examples/Pods/MapboxCommon/MapboxCommon.xcframework/ios-arm64_armv7/MapboxCommon.framework/MapboxCommon (2 slices)
ld: warning: ignoring file /Users/kavehmohammadpour/Desktop/MapBox-Test/mapbox-navigation-ios-examples/Pods/MapboxNavigationNative/MapboxNavigationNative.xcframework/ios-arm64_armv7/MapboxNavigationNative.framework/MapboxNavigationNative, missing required architecture x86_64 in file /Users/kavehmohammadpour/Desktop/MapBox-Test/mapbox-navigation-ios-examples/Pods/MapboxNavigationNative/MapboxNavigationNative.xcframework/ios-arm64_armv7/MapboxNavigationNative.framework/MapboxNavigationNative (2 slices)

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_MBXWaypoint", referenced from:
      objc-class-ref in RouteController.o
  "_OBJC_CLASS_$_MBXUpcomingRouteAlert", referenced from:
      objc-class-ref in RouteController.o
  "_OBJC_CLASS_$_MBXMapMatch", referenced from:
      objc-class-ref in PassiveLocationDataSource.o
  "_OBJC_CLASS_$_MBXTilesConfig", referenced from:
      objc-class-ref in OfflineDirections.o
      objc-class-ref in PassiveLocationDataSource.o
      objc-class-ref in RouteController.o
  "_OBJC_CLASS_$_MBXActiveGuidanceOptions", referenced from:
      objc-class-ref in RouteController.o
  "_OBJC_CLASS_$_MBXAccounts", referenced from:
      objc-class-ref in MBXAccounts+CoreNavigationAdditions.o
      __OBJC_$_CATEGORY_MBXAccounts_$_CoreNavigationAdditions in MBXAccounts+CoreNavigationAdditions.o
      objc-class-ref in NavigationService.o
  "_OBJC_CLASS_$_MBXFixLocation", referenced from:
      objc-class-ref in PassiveLocationDataSource.o
      objc-class-ref in RouteController.o
  "_OBJC_CLASS_$_MBXTileEndpointConfiguration", referenced from:
      objc-class-ref in PassiveLocationDataSource.o
  "_MBXAccountsSKUIDNavigationUser", referenced from:
      +[MBXAccounts(CoreNavigationAdditions) load] in MBXAccounts+CoreNavigationAdditions.o
  "_OBJC_CLASS_$_MBXNavigatorConfig", referenced from:
      objc-class-ref in OfflineDirections.o
      objc-class-ref in PassiveLocationDataSource.o
      objc-class-ref in RouteController.o
  "_OBJC_CLASS_$_MBXNavigator", referenced from:
      objc-class-ref in OfflineDirections.o
      objc-class-ref in PassiveLocationDataSource.o
      objc-class-ref in RouteController.o
  "_OBJC_CLASS_$_MBXSettingsProfile", referenced from:
      objc-class-ref in OfflineDirections.o
      objc-class-ref in PassiveLocationDataSource.o
      objc-class-ref in RouteController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by 1ec5** [comment]
Looks like the same thing as mapbox/mapbox-navigation-ios#2674.
